/*

**********************************
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1,2,3,5,8,13,21,34,55,89,...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-values terms.
**********************************

*/

#include <iostream>

int main(){

	int sum=0, k=0, i=0, j=1, limit;
	std::cout<<"Enter the limit: ";
	std::cin>>limit;
	while(j<=limit){
		k = i + j;
		if(k % 2 == 0)
			sum = sum+k;
		i=j;
		j=k;
	}
	std::cout<<"The sum: "<<sum<< std::endl;
	return 0;
}
